### ISSUE TITLE
Problem During submission

### ISSUE THREAD

**Issue by Zhangyong-Tang** [votchallenge/toolkit#101]
Hi, the submission is always failed, and in the forum, one of the authors said some issues have been detected, 4 days ago.
But currently the submission is still the same, failed to upload files.
So i wonder when will this problem be fixed?
Thanks in advance

**Comment by alanlukezic** [comment]
Hi, thank you for letting us know about the issue you have with the submission. We are exploring the situation and will let you know when we find out more. In the meantime, are you using the latest toolkit version (0.6.3)? And the latest TraX library (4.0.1)? Are you using the "vot pack" command to pack the results obtained on the VOTS23 dataset with 144 sequences?

**Comment by KhanhTungTran** [comment]
Hi, can you provide more information to this email address: _aihub.admin@openfactor.org_ (the official email to handle issues related to the evaluation server).

I will need more information, including the error message shown on the server, and if possible, your output zip file of **vot pack**.

Thanks.

**Comment by Zhangyong-Tang** [comment]
Thanks, i have sent the email right now.

**Comment by matejkristan** [comment]
A followup on the solution for this issue that might help other participants: The issue was likely due to the firewall setting on the participant side that prevented uploading to the server.
