### ISSUE TITLE
Meet an error using vot evaluate

### ISSUE THREAD

**Issue by tdd233** [votchallenge/toolkit#103]
Hi, I tried to use vot2022 to test my own tracker but some errors occurred. When I runed "vot test" to check the error, I found it seems that the toolkit can't identify my tracker(vipt_deep). Here is my trackers.ini file:
[vipt_deep] # <tracker-name>
label = vipt_deep
protocol = traxpython
command =  vipt_baseline
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
paths = /media/image/tdh/ViPT-main/lib/test/vot/

And here is the error:
![image](https://github.com/votchallenge/toolkit/assets/93235196/7f642a0f-b79e-4fc7-b1a5-0d49804aa20f)
Could you please help me solve the problem? Thanks a lot!!!

**Comment by lukacu** [comment]
There seem to be two issues here, the first one is related to the fact that you need trax package installed (vot-trax on pypi) in the environment of the tracker.

The second issue seems to be related to lack of testing on single-object sequences at the moment. I have pushed some changes to the toolkit main branch, but you will have to install a version from Github directly.

**Comment by lukacu** [comment]
It looks like you are using an old version of vot.py from the integration repository. Please update it.

**Comment by tdd233** [comment]
Sorry to bother you again. I already update my vot.py to 2023 version. But there is another error occurred "Evaluation interrupted by tracker error: ('Experiment interrupted', TrackerException(TraxException('Server terminated the session')))". The log file shows as below:
![image](https://github.com/votchallenge/toolkit/assets/93235196/831308c4-7539-4a0a-a447-710dc0e8a706)

**Comment by lukacu** [comment]
Please do not post screenshots, it is hard to see the entire log this way. Past formatted output as text. It looks like you are trying to run on of the old challenges with the new toolkit. With the lack of resources, we have now focused primarily on VOTS2023 and will get back to older challenges after the challenge is over. You may want to perhaps use an older versions of the toolkit (0.5.x) for now.

**Comment by lukacu** [comment]
Closing as no feedback was given.
