### ISSUE TITLE
Install the latest version of the toolkit problem

### ISSUE THREAD

**Issue by davidyang180** [votchallenge/toolkit#104]
Hi! Installing the latest version of the toolkit, but currently only 4.0.0 of the trax package is built.
```
ERROR: Could not find a version that satisfies the requirement vot-trax>=4.0.1 (from vot-toolkit) (from versions: 3.0.0, 3.0.1, 3.0.2, 3.0.3, 4.0.0)
ERROR: No matching distribution found for vot-trax>=4.0.1
```

**Comment by lukacu** [comment]
I do not know why this is a problem for you: https://pypi.org/project/vot-trax/4.0.1/ . Did you install trax from github directly?
