### ISSUE TITLE
succesfully submitted and finished but can not view my results

### ISSUE THREAD

**Issue by JornyWan** [votchallenge/toolkit#105]
the page jump into an error page showing the following info:
Access to eu.aihub.ml was denied
You don't have authorization to view this page.

How to get my result on server when it turned to finished.

**Comment by KhanhTungTran** [comment]
Hi,

You will get your results through email (the one you registered through Google Form), and not on the server.

**Comment by JornyWan** [comment]
> 

hi, but i didn't receive my results in my email yet(i had submitted for several days...), while the page showed that analysis successfully.

**Comment by JornyWan** [comment]
sorry, it sent to my junk email... thank you for your time.
