### ISSUE TITLE
VOTSTS2022 Annotation Format

### ISSUE THREAD

**Issue by iremonur** [votchallenge/toolkit#107]
Hi, I want to evaluate a tracker on the VOTSTS-2022 dataset. The segmentation annotations are placed under the gorundtruth.txt but I could not understand the format and find an explanation for it. For example, the annotation format is as in below:

m242,164,118,115,29,1,2,1,110,45,73,61,56,69,47,76,41,81,36,83,34,85,33,86,32,86,32,87,30,88,29,90,28,90,27,92,26,92,26,93,25,93,25,94,23,95,22,97,20,98,20,98,19,100,18,100,18,100,17,101,17,102,15,103,15,104,14,104,14,104,13,105,13,105,10,109,9,109,9,109,9,110,8,111,7,112,6,112,6,111,6,112,5,113,5,113,4,115,1,117,1,117,1,117,1,115,3,115,3,115,3,115,3,115,3,115,3,115,3,115,3,115,3,115,2,116,3,115,3,115,2,116,3,115,3,115,3,116,2,116,2,116,2,116,2,116,2,116,2,116,2,116,2,116,2,116,2,116,1,117,1,116,2,116,2,116,2,116,2,116,2,116,2,116,2,116,2,116,2,116,2,116,2,116,2,116,2,116,2,116,2,115,3,16,3,96,3,16,3,14,10,72,3,16,3,13,18,65,3,16,5,10,20,13,26,25,3,16,9,3,24,9,30,24,3,16,38,6,31,24,3,17,38,3,34,23,3,17,76,22,3,17,76,22,3,16,77,22,3,15,78,22,3,14,79,22,3,15,78,22,3,14,79,22,4,12,80,22,4,11,82,21,5,9,84,20,99,19,100,17,102,15,104,12,107,10,8

What does m242 mean? And what do these points represent? I assume that they represent the segmentation pixel points but are they ordered like x,y,x,y...x,y pixel coordinates? I tried to create binary segmentation masks considering they are ordered x,y.. but the mask obtained by these points does not represent the object. Could you please explain the annotation format for VOTSTS2022? 
I would be glad if you help me with this.

**Comment by lukacu** [comment]
It is a RLE encoded mask with an offset, the code for serailization is available in vot/region/io.py .
