### ISSUE TITLE
failed to evaluate integration tracker - 'SingleObject' object has no attribute '__name__'

### ISSUE THREAD

**Issue by barnoy1** [votchallenge/toolkit#108]
vot fails when trying to evaluate the integration python tracker provided in the [intergration repo](https://github.com/votchallenge/integration). 

upon evaluation using the following command line:
```bash
vot evaluate --workspace . NCCPython
```

vot generates an error implying the tracker is not valid (name attribute missing):
```bash
'SingleObject' object has no attribute '__name__'
Traceback (most recent call last):
  File "/home/ronbar/repo/vot/venv/lib/python3.8/site-packages/vot/utilities/cli.py", line 445, in main
    do_evaluate(args)
  File "/home/ronbar/repo/vot/venv/lib/python3.8/site-packages/vot/utilities/cli.py", line 228, in do_evaluate
    run_experiment(experiment, tracker, workspace.dataset, config.force, config.persist)
  File "/home/ronbar/repo/vot/venv/lib/python3.8/site-packages/vot/experiment/__init__.py", line 339, in run_experiment
    transformed.extend(experiment.transform(sequence))
  File "/home/ronbar/repo/vot/venv/lib/python3.8/site-packages/vot/experiment/__init__.py", line 276, in transform
    get_logger().debug("Transforming sequence {} with transformer {}.{}".format(sequence.identifier, transformer.__module__, transformer.__name__))
AttributeError: 'SingleObject' object has no attribute '__name__'

```

below are the system requirements and detailed steps to reproduce.
Thank you in advance.

----------------------------------------------------------------------------------------------------------------------------------------------------------

system info:
---------------
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Kernel: 5.15.0-48-generic #54~20.04.1-Ubuntu SMP Thu Sep 1 16:17:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

steps to reproduce:
-------------------------

<h3>1. bring up</h3>
install latest vot-toolkit  into project venv

```python
pip install vot-toolkit
```

<h3>2. create workspace</h3>

creating new workspace named *tracker_ws*, and create workspace with basic sequences
```python
vot initialize --workspace tracker_ws tests/basic
```

<h3>3. integration</h3>
integrate vot with default tracker as described in [support page](https://www.votchallenge.net/howto/integration_multiobject.html)

3.1 download integration code into target project
```bash
git clone git@github.com:votchallenge/integration.git
```
3.2 configure tracker_ws/trackers.ini file to the default python tracker

```ini
[NCCPython]
label = PyNCC
protocol = traxpython
command = ncc_multiobject_manager
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
paths = <FULL_PATH>/integration/python
# Additional environment paths
env_PATH = /usr/local/lib;<FULL_PATH>/integration/python;<FULL_PATH>/trax/build;${PATH}
```

<h3>4. sanity check</h3>
testing if tracker is identified.

running vot test inside the workspace reveal that the tracker is present:
```bash
cd tracker_ws 
vot test
```bash
List of found trackers: 
 * NCCPython
```

<h3>5. evaluate tracker: FAILED</h3>
At this point I tried to run evaluate on this tracker:

```bash
vot evaluate --workspace . NCCPython
```

and got the following error
```bash
'SingleObject' object has no attribute '__name__'
Traceback (most recent call last):
  File "/home/ronbar/repo/vot/venv/lib/python3.8/site-packages/vot/utilities/cli.py", line 445, in main
    do_evaluate(args)
  File "/home/ronbar/repo/vot/venv/lib/python3.8/site-packages/vot/utilities/cli.py", line 228, in do_evaluate
    run_experiment(experiment, tracker, workspace.dataset, config.force, config.persist)
  File "/home/ronbar/repo/vot/venv/lib/python3.8/site-packages/vot/experiment/__init__.py", line 339, in run_experiment
    transformed.extend(experiment.transform(sequence))
  File "/home/ronbar/repo/vot/venv/lib/python3.8/site-packages/vot/experiment/__init__.py", line 276, in transform
    get_logger().debug("Transforming sequence {} with transformer {}.{}".format(sequence.identifier, transformer.__module__, transformer.__name__))
AttributeError: 'SingleObject' object has no attribute '__name__'

```

**Comment by lukacu** [comment]
Yes, the current main branch has some problems with old challenges that we are trying to address, but time is limited. It is best to try using 0.5.X and trax 3.X . Or wait for August when we will finally have time to fix this issue.

**Comment by Tchuanm** [comment]
Great, 0.5.x is useful for evaluate vot2020。

**Comment by lukacu** [comment]
Both can be installed from pypi by pinning the version of the package. No need to explicitly build anything, just browse the version list and select the most recent one that suits the requirement that I wrote.

**Comment by lukacu** [comment]
I have now gone through previous challenges and datasets and fixed all errors that I have encountered. Please test version 0.6.5 if the errors are gone.
