### ISSUE TITLE
evaluating problem

### ISSUE THREAD

**Issue by faicaiwawa** [votchallenge/toolkit#109]
when i evaluated the rgbd test , it gave me this error information . i do have 'color' and 'depth' dir. in workplace. should i set the path to dataset?

> 
> Scanning registry /home/qiuyang/ViPT/vot22_RGBD_workspace/trackers.ini
> Found 1 trackers
> Generating dummy sequence
> Obtaining runtime for tracker vipt_deep
> Initializing tracker (1/3)
> Running process: /home/qiuyang/anaconda3/envs/vipt/bin/python -m vipt_baseline
> test config:  {'MODEL': {'PRETRAIN_FILE': './pretrained/OSTrack_ep0300.pth.tar', 'EXTRA_MERGER': False, 'RETURN_INTER': False, 'RETURN_STAGES': [], 'BACKBONE': {'TYPE': 'vit_base_patch16_224_ce_prompt', 'STRIDE': 16, 'MID_PE': False, 'SEP_SEG': False, 'CAT_MODE': 'direct', 'MERGE_LAYER': 0, 'ADD_CLS_TOKEN': False, 'CLS_TOKEN_USE_MODE': 'ignore', 'CE_LOC': [3, 6, 9], 'CE_KEEP_RATIO': [0.7, 0.7, 0.7], 'CE_TEMPLATE_RANGE': 'CTR_POINT'}, 'HEAD': {'TYPE': 'CENTER', 'NUM_CHANNELS': 256}}, 'TRAIN': {'PROMPT': {'TYPE': 'vipt_deep'}, 'LR': 0.0004, 'WEIGHT_DECAY': 0.0001, 'EPOCH': 60, 'LR_DROP_EPOCH': 48, 'BATCH_SIZE': 32, 'NUM_WORKER': 10, 'OPTIMIZER': 'ADAMW', 'BACKBONE_MULTIPLIER': 0.1, 'GIOU_WEIGHT': 2.0, 'L1_WEIGHT': 5.0, 'FREEZE_LAYERS': [0], 'PRINT_INTERVAL': 50, 'VAL_EPOCH_INTERVAL': 5, 'GRAD_CLIP_NORM': 0.1, 'AMP': False, 'FIX_BN': True, 'SAVE_EPOCH_INTERVAL': 5, 'SAVE_LAST_N_EPOCH': 1, 'CE_START_EPOCH': 4, 'CE_WARM_EPOCH': 16, 'DROP_PATH_RATE': 0.1, 'SCHEDULER': {'TYPE': 'step', 'DECAY_RATE': 0.1}}, 'DATA': {'SAMPLER_MODE': 'causal', 'MEAN': [0.485, 0.456, 0.406], 'STD': [0.229, 0.224, 0.225], 'MAX_SAMPLE_INTERVAL': 200, 'TRAIN': {'DATASETS_NAME': ['DepthTrack_train'], 'DATASETS_RATIO': [1], 'SAMPLE_PER_EPOCH': 60000}, 'VAL': {'DATASETS_NAME': ['DepthTrack_val'], 'DATASETS_RATIO': [1], 'SAMPLE_PER_EPOCH': 10000}, 'SEARCH': {'SIZE': 256, 'FACTOR': 4.0, 'CENTER_JITTER': 3, 'SCALE_JITTER': 0.25, 'NUMBER': 1}, 'TEMPLATE': {'NUMBER': 1, 'SIZE': 128, 'FACTOR': 2.0, 'CENTER_JITTER': 0, 'SCALE_JITTER': 0}}, 'TEST': {'TEMPLATE_FACTOR': 2.0, 'TEMPLATE_SIZE': 128, 'SEARCH_FACTOR': 4.0, 'SEARCH_SIZE': 256, 'EPOCH': 60}}
> ['path']
> @@TRAX:hello "trax.name=" "trax.family=" "trax.image=path;" "trax.region=rectangle;" "trax.description=" "trax.version=4" "vot=python" "trax.channels=color;depth;" 
> Frame does not have information for channel: depth
> Traceback (most recent call last):
>   File "/home/qiuyang/anaconda3/envs/vipt/lib/python3.7/site-packages/vot/utilities/cli.py", line 384, in main
>     do_test(args)
>   File "/home/qiuyang/anaconda3/envs/vipt/lib/python3.7/site-packages/vot/utilities/cli.py", line 90, in do_test
>     region, _, _ = runtime.initialize(sequence.frame(0), sequence.groundtruth(0))
>   File "/home/qiuyang/anaconda3/envs/vipt/lib/python3.7/site-packages/vot/tracker/trax.py", line 429, in initialize
>     return self._process.initialize(frame, region, tproperties)
>   File "/home/qiuyang/anaconda3/envs/vipt/lib/python3.7/site-packages/vot/tracker/trax.py", line 251, in initialize
>     tlist = convert_frame(frame, self._client.channels)
>   File "/home/qiuyang/anaconda3/envs/vipt/lib/python3.7/site-packages/vot/tracker/trax.py", line 78, in convert_frame
>     raise DatasetException("Frame does not have information for channel: {}".format(channel))
> vot.dataset.DatasetException: Frame does not have information for channel: depth
> @@TRAX:quit

**Comment by lukacu** [comment]
Please see #108 for now, we are testing all past challenges to see what are the problems, but it is holiday season and things are progressing slowly.

**Comment by faicaiwawa** [comment]
> Please see #108 for now, we are testing all past challenges to see what are the problems, but it is holiday season and things are progressing slowly.

Thank you for your assistance. With your help, I was able to successfully run the VOT toolkit after changing the Trax version. However, I have encountered a new issue where the tracker's inference speed for VOT testing is extremely slow. I am certain that this is not the normal speed for my tracker. Could you please advise on what could typically cause such slow speeds?
![Screenshot from 2023-08-01 20-50-10](https://github.com/votchallenge/toolkit/assets/117245509/80336885-c59a-4355-8db4-d39946a54870)
