### ISSUE TITLE
groundtruth.txt formats not contain bounding box

### ISSUE THREAD

**Issue by barnoy1** [votchallenge/toolkit#111]
vots2023 stack groundtruth.txt file not contain bounding box.

## setup

versions:
vot-trax                  4.0.1
vot-toolkit               0.6.4

## steps to reproduce on vs2023 stack:

1. download vot initalize on vots2023 stack
```python

(venv) root@L-P-RONBAR-LW:/home/ronbar/repo/vot-toolkit-sample# vot initialize --workspace ws_vot2023 vots2023
Downloading sequence dataset "VOTS2023 Challenge" with 144 sequences (total 26.0GiB).
 Downloading          |████ 
...   
Successfully downloaded all sequences.
Download completed
Initialized workspace in 'ws_vot2023'
```

groundtruth.txt inside the sequences no containing boundingbox. In the 
[docs/overview.rst](https://github.com/votchallenge/toolkit/blob/master/docs/overview.rst) it is specified that 
`
The groundtruth file is a text file that contains one line per frame. Each line contains the bounding box of the object in the frame in the format x,y,w,h.
`
this is not the format found in the downloaded groundtruth.txt files.

I attached the animal sequence for reference but this happens to all sequences

```ini
channels.color=color/%08d.jpg
format=default
fps=30
name=animal
uid=e034acc5f1fb8097540b821b6bf66d32efa830f43bf425950386b6caa480bc8ba0a717c03c95adb12e8e7bdd70c1c5f01e56fc43be81d0158e188531f9ac23b7

```
[groundtruth.txt](https://github.com/votchallenge/toolkit/files/12299306/groundtruth.txt)

the content of this file contains in the first row the following: m802,246,48,25,1,7,41,9,38,12,36,13,35,22,26,37,11,41,7,43,5,44,4,45,3,46,3,46,3,45,4,45,4,3,2,38,11,32,17,30,19,29,20,13,4,11,21,4,3,5,4,11,21,4,4,4,4,12,21,3,4,5,5,10,21,3,5,6,7,6,21,3,5,6,34,3,5,6,19
0
0
0
..
0

**Comment by lukacu** [comment]
The annotations can also be segmentation, in this case we encode them as RLE encoded binary mask fragment. The format is a bit specific and is probably not documented completely yet. The documentation for the toolkit is also WIP and probably does not reflect the fast pace of development, instead it reflects the lack of manpower :)
