### ISSUE TITLE
VOT-TIR 2016 Dataset disappeared?

### ISSUE THREAD

**Issue by AaronLReid** [votchallenge/toolkit#112]
Hi there,

I am trying to use the toolkit to benchmark against the VOT TIR 2016 dataset, but it appears the download fails.

The link in the yaml file is no longer active, and it is not a json like the others. Is there some way to download this dataset please?

**Comment by self-memory** [comment]
I'm having the same problem.

**Comment by self-memory** [comment]
> 
[](http://data.votchallenge.net/vot2016/vot-tir2016.zip)   
This url will say "404 not found"

**Comment by self-memory** [comment]
http://data.votchallenge.net/vot2016/vot-tir2016.zip
This url will say "404 not found"

**Comment by lukacu** [comment]
Hi, I can confirm that the dataset is indeed missing on our server. I am not sure what happened, but we will try to find it and recover it ...

**Comment by self-memory** [comment]
Thanks for your reply, looking forward to your solution!

**Comment by lukacu** [comment]
I have now assembled the 2016 TIR dataset and uploaded it again. I am sorry that it took so long. The correct URL is available in the dev channel, which will eventually be merged.
