### ISSUE TITLE
Data license

### ISSUE THREAD

**Issue by eran-deci** [votchallenge/toolkit#117]
Hi,
I noticed the license for this repo, which I assumes relates to the code.
What is the license for the different challenges' data itself?
I couldn't find information about it online.

**Comment by lukacu** [comment]
Hello, thanks for the interest. Yes, the license is only applicable to the code.  As for the datasets, we can only allow them to be used to evaluate tracking algorithms. A lot of sequences were repurposed for other tracking benchmarks through consolidation procedures. However, generally, the evaluation use cases are considered non-problematic.

If you need more information, please use other channels to contact us, the issue tracker is used for toolkit related stuff.
