### ISSUE TITLE
Vot 2024 evaluate problem

### ISSUE THREAD

**Issue by Cevikalp** [votchallenge/toolkit#124]
We keep getting the following error. Any solution for this?
Evaluation interrupted by tracker error: ('Experiment interrupted', TrackerException('Tracker interrupted, it did not reply in 30 seconds'))

**Comment by lukacu** [comment]
This is a common error for trackers with slow reply times (it may also be just for the first frame). You can increase the timeout parameters in the tracker config file to a larger number (the default is 30 seconds).

**Comment by lukacu** [comment]
If you manged to solve the problem, please close the issue.

**Comment by Cevikalp** [comment]
it is solved, thank you.
