### ISSUE TITLE
Error when I run evaluation on the default python tracker

### ISSUE THREAD

**Issue by Abdelpakey** [votchallenge/toolkit#18]
Hi Luca,

I'm using vot-toolkit-python and I have the latest commitments from the dev branch. When I run  evaluation on the default python tracker:
    
       vot evaluate  --workspace '/home/user/Desktop/vot2020/vot-workspace'  NCCPython

 It gives me this error

raise AttributeError("Missing arguments: {}".format(", ".join(unspecified)))
AttributeError: Missing arguments: low, high

Any help would be appreciated!

**Comment by lukacu** [comment]
Experiment stacks should be fixed now in dev branch, this looks like an issue related to that.
