### ISSUE TITLE
Analysis with "votlt2020" stack leads to TypeError

### ISSUE THREAD

**Issue by daniel-d-koenig** [votchallenge/toolkit#23]
Evaluating a tracker using the "votlt2020" stack leads to following error:

`Traceback (most recent call last):
  File "/home/username/.conda/envs/vot_testing/lib/python3.7/site-packages/vot/analysis/processor.py", line 99, in __call__
    return self._analysis.join(self._experiment, self._trackers, self._sequences, self._results)
  File "/home/username/.conda/envs/vot_testing/lib/python3.7/site-packages/vot/analysis/__init__.py", line 327, in join
    transformed_results[i] = results[i][0, 0]
TypeError: tuple indices must be integers or slices, not tuple`

I suppose that this is a bug related to the commit (f4dd567c232), which introduces returning analysis data as grid.

I assume that following code line is only meant to convert from `List` to `Grid` an therefore the `[0, 0]` has to be removed:
https://github.com/votchallenge/vot-toolkit-python/blob/c764ff373d173c697e83f907423f05d90f6f647e/vot/analysis/__init__.py#L326

Best regards,
Daniel

**Comment by shen338** [comment]
Same thing happens to me! How did you solve this? 

@lukacu Could you take a look on this? Thank you!

**Comment by daniel-d-koenig** [comment]
I just removed `[0, 0]` then the above mentioned line looks like:
`transformed_results[i] = results[i]`
but I am not sure whether it is the correct solution. My results looked plausible.

**Comment by shen338** [comment]
Cool! The result looks good to me. Thank you!

**Comment by lukacu** [comment]
I am closing this issue since the entire task splitting has been changed since the issue was opened.
