### ISSUE TITLE
test multiple algorithm

### ISSUE THREAD

**Issue by kongbia** [votchallenge/toolkit#27]
How to test multiple algorithms simultaneously using multiple GPUs?

**Comment by lukacu** [comment]
At the moment there is no mechanism that would allow this, it is not even possible to run a single tracker in parallel. We will get to this eventually, but at the moment if you want to run multiple trackers, you have to run each tracker separately and assign GPUs using CUDA_VISIBLE_DEVICES variable prior to running CLI command for each tracker. I think this should work.

**Comment by kongbia** [comment]
I see. Thank you very much!
