### ISSUE TITLE
Evaluate problem

### ISSUE THREAD

**Issue by xuqingyu26** [votchallenge/toolkit#28]
Hello, recently, i am working on the rgbt challenge, and when i try to run my tracker using the vot-toolkit-python, i run into some problems, as follows:

Checking for new version
Unable to retrieve version information HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /votchallenge/vot-toolkit-python/master/vot/version.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efcbb8b5050>: Failed to establish a new connection: [Errno 111] Connection refused'))
Downloading sequence dataset "VOT2020 RGBTIR Challenge" with 60 sequences.

#########
then, i download the rgbt dataset offline, and set it as the official one, but, the problem above still remains, how can i fix it?

**Comment by hongsheng-Z** [comment]
Hi, Did you solve this problem, I have the same situation as you.

**Comment by lukacu** [comment]
Is this the entire stack trace? It looks like the toolkit fails to check for updates, but then it starts downloading sequences, what happens after that, is there an error?

**Comment by lukacu** [comment]
No response provided, closing issue.
