### ISSUE TITLE
vot: error: argument action: invalid choice: 'workspace'

### ISSUE THREAD

**Issue by MACILLAS** [votchallenge/toolkit#30]
I'm following the standard installation procedure. I've successfully installed vot-toolkit-python... However when I try to run 
``` 
mkdir vot-workspace
vot workspace vot2020 --workspace /Content/vot-workspace/
```

I get:
usage: vot [-h] [--debug] [--registry REGISTRY]
           {test,initialize,evaluate,analysis,pack} ...
vot: error: argument action: invalid choice: 'workspace' (choose from 'test', 'initialize', 'evaluate', 'analysis', 'pack')

please advise.

**Comment by MACILLAS** [comment]
I think I got it. Instead of workspace its initialize?
The documentation should be updated...

**Comment by lukacu** [comment]
This was fixed in our documentation
