### ISSUE TITLE
How to compute the robustness in the A-R plot?

### ISSUE THREAD

**Issue by ShengYun-Peng** [votchallenge/toolkit#35]
Hi @lukacu, could you point me to the code on computing the robustness and failures? Is the robustness the reliability metric you mentioned in the 2014 "Is my new tracker really better than yours?" paper?

**Comment by lukacu** [comment]
The code is available here: https://github.com/votchallenge/toolkit/blob/master/vot/analysis/supervised.py . There are now two measures called robustness, one of the supervised experiment (this is from the 2014 paper) and the new based on periodic restarts on anchor frames (the code for this one is available in the multistart.py).
