### ISSUE TITLE
Initialize workspace stuck at downloading

### ISSUE THREAD

**Issue by SimJJ96** [votchallenge/toolkit#41]
I have followed the steps mentioned in the tutorial to initalize the workspace. However my downloading for the data have stuck for a long time as shown in the figure. 
![image](https://user-images.githubusercontent.com/77402245/149929466-9d068fde-9cec-41b8-87a2-ecb053187562.png)

**Comment by lukacu** [comment]
Well, the sequences are downloaded one by one. If you run with debug flag, do you see any info regarding which sequence is problematic?

**Comment by SimJJ96** [comment]
Thanks for the reply. I have solved it by reinstalling the VOT package again.
