### ISSUE TITLE
T`ypeError: reflection_pad2d() in VOT toolkit

### ISSUE THREAD

**Issue by tahiira** [votchallenge/toolkit#46]
Hello, I am trying to test the RLT-DiMp tracker with vot dataset. when I want run the vot test DiMP, I faced with this error:
`
T`ypeError: reflection_pad2d(): argument 'padding' must be tuple of ints, but found element of type float at pos 1`
`
how can I remove this?

**Comment by lukacu** [comment]
This function is not a part of the toolkit, it must be a tracker issue. Therefore this is not a toolkit issue and I am closing the ticket. Please contact tracker authors if you have problems with their code.
