### ISSUE TITLE
VOT2022 challenge Long Term data Not Found

### ISSUE THREAD

**Issue by jcaha** [votchallenge/toolkit#51]
The data description json to download vot2022 lt sequences seems to be inaccessible now. The url in vot toolkit is https://data.votchallenge.net/vot2022/lt/description.json. And here is the page:
![lt](https://user-images.githubusercontent.com/18487284/160272110-80feb7e8-964a-4ebb-b41f-bac356be662f.PNG)

How can I solve it? Thanks for your work.

**Comment by lukacu** [comment]
Yes, as mentioned in the announcement, the LT challenge will open with a bit of delay, probably on Monday or Tuesday. Please wait until then.
