### ISSUE TITLE
The stack of VOT2022 

### ISSUE THREAD

**Issue by EavanLi** [votchallenge/toolkit#54]
I'm sorry when I create a workspace, the stack of VOT2022 will appear "Experiment stack None not found". 
For example:  vot initialze lt --workspace <workspace-path>, it will appear "Experiment stack None not found". 
Very hope you can tell me how to configure it properly. Thank you!

**Comment by xiaozai** [comment]
vot initialize vot2022/lt --workspace

**Comment by EavanLi** [comment]
Sorry to bother you with such a small question, thank you very much!

**Comment by xiaozai** [comment]
vot initialize vot2022/lt --workspace

Yifan Li ***@***.***> 于 2022年4月14日周四 15:54写道：
