### ISSUE TITLE
grace: 3 in vot2020.yaml

### ISSUE THREAD

**Issue by xjtuwh** [votchallenge/toolkit#64]
vot/stack/vot2020.yaml  
realtime:
    type: multistart
    realtime:
      grace: 3
Hello, can you tell me what the grace: 3 mean?

**Comment by xjtuwh** [comment]
@lukacu @alanlukezic

**Comment by lukacu** [comment]
If I remember correctly grace parameter is used in real-time tracking to tell the toolkit how many frames can "misbehave" after the initialization. This was introduced to give slow warmup tracker a chance to perform a bit better, but it is not needed if the tracker is written correctly.
