### ISSUE TITLE
What the contents of the groundtruth.txt file represent?

### ISSUE THREAD

**Issue by DjangoChaogh** [votchallenge/toolkit#76]
Whether the target information (usually in the form of bounding box or mask) in the first frame is given in the groundtruth.txt file of each sequence? If so, what is the meaning of each number in the txt file?

![jietu](https://github.com/votchallenge/toolkit/assets/42630571/fb75dec3-d4d2-41fe-b6e8-f58b793e1258)

**Comment by franktpmvu** [comment]
it's a mask of GT, if you want decode it, The code for mask IO is available in vot/region/io.py.
https://github.com/votchallenge/toolkit/issues/24#issuecomment-738851025

**Comment by lukacu** [comment]
Yes, it is a RLE encoding of a mask with some metadata (region size, offset).
