### ISSUE TITLE
About vot initialize tests/multiobject

### ISSUE THREAD

**Issue by wooksu** [votchallenge/toolkit#77]
Why is there no gt every frame in the groundtruth of the dataset obtained through vot initialize tests/multiobject?
<img width="1551" alt="스크린샷 2023-05-17 오전 1 03 48" src="https://github.com/votchallenge/toolkit/assets/106130258/d57526b9-745c-4ddd-99e1-82923aca6f7b">

**Comment by lukacu** [comment]
Because we did not annotate all frames, this also means that not all frames are used in analysis.
