### ISSUE TITLE
No results are generarated by vot analysis

### ISSUE THREAD

**Issue by yahooo-m** [votchallenge/toolkit#78]
I have generated some results named *_time.value and *.bin in "results/Tracker/*(sequences)". But when I use vot analysis, the generated analysis json file has no results about the tracker. And there is no error when I use vot analysis. So I have the following questions:
1、Whether the results file generated are correctly?
2、Why is there no result about the analysis?
<img width="468" alt="屏幕截图 2023-05-18 105903" src="https://github.com/votchallenge/toolkit/assets/27918565/2f1a830d-a67a-415b-a393-3ef75e21c605">

**Comment by yahooo-m** [comment]
I know why....
So when will your group give the platform for evaluation?

**Comment by lukacu** [comment]
It was supposed to be up since the start of the week, but there have been some last minute issues since the dataset is quite large. We hope that it will be online before the end of the week. We will then discuss if any changes to the challenge timeline are possible.
