### ISSUE TITLE
vot evaluate problem!!

### ISSUE THREAD

**Issue by Zhangyong-Tang** [votchallenge/toolkit#80]
The method is always stopped at    '  request = self._trax.wait()  '  .
Wether it is correct that this step takes a long time or not?
![issue-wait](https://github.com/votchallenge/toolkit/assets/28916428/2020342c-4cd5-405a-9f21-280f4659a920)

**Comment by Zhangyong-Tang** [comment]
The problem is '''unable to connect to tracker'''

**Comment by lukacu** [comment]
Please provide some more information on how did you integrate your tracker, perhaps share tracker config and wrapper code. From the current information we cannot really say much more than that there is an error in either wrapper or config.

**Comment by Zhangyong-Tang** [comment]
manager = vot.VOTManager(tracker, "mask")
    manager.run()

**Comment by Zhangyong-Tang** [comment]
[label]
label = label
protocol = traxpython
command = test_vots2023
paths = /data/Disk_A/zhangyong/VOT2023/master

**Comment by Zhangyong-Tang** [comment]
![image](https://github.com/votchallenge/toolkit/assets/28916428/04b4a141-7a42-4efc-bbaf-6f905cfbf030)

**Comment by Zhangyong-Tang** [comment]
i have tried on both the Ubantu and Windows systems, on two machines, but both stopped at this line.

**Comment by lukacu** [comment]
Did you run the CLI test? Can you show me the output that it produced to see what are the Trax messages? Also, did you try to run one of the demo trackers?

**Comment by Zhangyong-Tang** [comment]
![image](https://github.com/votchallenge/toolkit/assets/28916428/5b8b1ebd-8d67-4f53-84a4-de333ff7c4db)
I have passed the CLI TEST. Everything seems well.

**Comment by lukacu** [comment]
Yes, this is indeed strange, the test should be more or less the same thing. Can you try perhaps also running test with a real sequence (you can specify a sequence path and point it to one of the real sequences in VOTS2023 dataset). So far I have no idea what could be the problem.

**Comment by davidyang180** [comment]
> Yes, this is indeed strange, the test should be more or less the same thing. Can you try perhaps also running test with a real sequence (you can specify a sequence path and point it to one of the real sequences in VOTS2023 dataset). So far I have no idea what could be the problem.

Strangely, I had the same problem, but I was able to pass `request = self._trax.wait()` fine the other day, and when I ran the evaluation again today, I got this error.

**Comment by davidyang180** [comment]
> ![image](https://user-images.githubusercontent.com/28916428/239683905-5b8b1ebd-8d67-4f53-84a4-de333ff7c4db.png) I have passed the CLI TEST. Everything seems well.
> 
> Actually, it seems that 'vot evaluate name' haven't got in touch with my tracker, it just break during the connection process.

Hi! May I ask where this test script is mentioned? I don't seem to see it, I'll try this too.

**Comment by Zhangyong-Tang** [comment]
@davidyang180 
My script is 'vot test ncc'
Just follow the offical NCC test, but i only pass the test with the label in rectangle manner, failed in the mask manner

**Comment by davidyang180** [comment]
@Zhangyong-Tang 
I tried it in mask manner just now, and the error was reported as `Tracker does not exist`. rectangle manner label? Does the VOTS2023 dataset have rectangle label? Or did you test it with last year's VOT dataset.

**Comment by Zhangyong-Tang** [comment]
Use the python_ncc rather than the python_ncc_mask to pass the rectangle test.

**Comment by lukacu** [comment]
I will check all the examples in the integration repository, but note that some of them are not suitable for multi-object tracking.

**Comment by Zhangyong-Tang** [comment]
I think you can find this in one closed issue 76

**Comment by JornyWan** [comment]
> I think you can find this in one closed issue 76

Hi, i want to ask if you have used these four sequences to test the tracker? Are you using io files to decode and then testing?

Thanks.

**Comment by lukacu** [comment]
I am closing the topic now since it is not really an issue, discussion belongs to the forum.
