### ISSUE TITLE
Format of ground-truth about VOTS2023-dev dataset

### ISSUE THREAD

**Issue by davidyang180** [votchallenge/toolkit#81]
Hi! as can be seen from the figure below, the shape information provided by the VOTS2023-dev dataset starting with 'm' can finally decode the `region.mask` of the corresponding frame. However, the ground-truth marked with 0 or 1 are decoded in the `region.Special_object` format, and it seems that there is no specific mask information. What is the difference between this? Does the corresponding frame have mask information? How to use it when evaluating?
![image](https://github.com/votchallenge/toolkit/assets/45596935/6a0c4706-4fe1-4f5f-b13c-b29646538b24)
![image](https://github.com/votchallenge/toolkit/assets/45596935/d51c3e72-b9d9-4035-86bb-ea80b20dc2f2)

**Comment by lukacu** [comment]
Please see #77 , it has the same question. Not all frames are annotated, performance analysis is only done on annotated frames.
