### ISSUE TITLE
Failed to download 9 sequences

### ISSUE THREAD

**Issue by hkchengrex** [votchallenge/toolkit#84]
Hi, I am using v0.6.3 to run the command `vot initialize vots2023 --workspace vots-ws` but during download I am getting a lot of 

```
File not available
Traceback (most recent call last):
  File "/home/hokeikc2/qt/toolkit/vot/dataset/vot.py", line 236, in download_dataset_meta
    download_uncompress(channel_url, channel_directory)
  File "/home/hokeikc2/qt/toolkit/vot/utilities/net.py", line 160, in download_uncompress
    download(url, tmp_file)
  File "/home/hokeikc2/qt/toolkit/vot/utilities/net.py", line 69, in download
    raise NetworkException("File not available")
vot.utilities.net.NetworkException: File not available
```

When the command finish running, it gives:
```
Failed to download 9 sequences.
Failed sequences: cat, diabolo, fernando, fish1, helicopter, motorcycle-18, rabbits, sheep-9, tank-9
Download completed
```

And there are no files in `vots-ws/cat/color/`, etc.

How should I download those missing videos?

Thanks!

**Comment by hkchengrex** [comment]
I tried on a different server (in a different physical location), and the same error happens but with a different set of sequences.

```
Failed to download 9 sequences.
Failed sequences: crab-18, crab-6, goldfish-3, gorilla-13, pool-15, rabbit, rabbit-10, umbrella-19, umbrella-9
```

**Comment by lukacu** [comment]
This is indeed interesting, the dataset is quite large and it seems that connection may break. We have tried to improve downloading, but it may still fail. In any case, the toolkit will try to download the remaining sequences if you trigger dataset loading (either by running evaluate or by deleting config and running initialize again).

**Comment by hkchengrex** [comment]
Thank you for the response. Happy to know that I can re-download them this way. Interestingly I also got "Error when downloading file, trying to resume download" (just once) as in #75, but those resume/retry automatically. It does not seem to retry automatically for "File not available" though.
