### ISSUE TITLE
Experiment stack None not found

### ISSUE THREAD

**Issue by Quan-w** [votchallenge/toolkit#85]
I use this command to initialize the vot 
`vot initialize vot2023 --workspace ./ --nodownload`
But reported this error:
`Experiment stack None not found` 
Thanks in advance。

**Comment by Quan-w** [comment]
my vot-toolikit is 0.6.2

**Comment by lukacu** [comment]
Stack name is vots2023

**Comment by KristianZZ** [comment]
Same problem with yours

**Comment by wsxbaaaa** [comment]
Did you solve the problem?
