### ISSUE TITLE
About current output format and filename format

### ISSUE THREAD

**Issue by davidyang180** [votchallenge/toolkit#87]
Hi! Because there are some bugs in my vot evaluation stage that have not been resolved, it is not clear what the format of the output file will be? Here I would like to ask in advance the output format and filename format in the current multi-target scenario.
In the previous multi-start single-target scene, the output format of the result is set to 1 for the first frame, and the prediction result of the subsequent frame is in the format of (x, y, w, h). The filename format is `*****_00000start_frame_number.txt` and `*****_00000start_frame_number_time.value`
But now it is changed to a multi-target scene. I would like to ask what is the current output format and filename format?

**Comment by lukacu** [comment]
The toolkit takes care of the format and correct result packing, it is not recommended to tamper with the actual manner of results storage. The structure of the experiment results is not documented as every experiment has a bit different format. But the format has indeed not changed much.
