### ISSUE TITLE
Sequence download fail

### ISSUE THREAD

**Issue by songtianhui** [votchallenge/toolkit#90]
When downloading sequences in workspace initialization, some downloads fail because of network problem.
For example, when download completed it shows message:
```
Failed to download 15 sequences.
Failed sequences: bag, basketball, bus-2, clownfish, colorfish, conduction1, duck, f1, hat-1, hat-5, orangefish, panda, pig-2, stripedfish, tennis
```
How can I correct it and make completion?

**Comment by lukacu** [comment]
Please look at other (closed) issues regarding this. It may happen that some sequences fail at some point, but they will be downloaded before the real evaluation can begin.
