### ISSUE TITLE
The context of the output .bin file?

### ISSUE THREAD

**Issue by Zhangyong-Tang** [votchallenge/toolkit#94]
Hello! With your kind help, i have passeed the mask ncc example, thank you very much.

But some other prooblems appear.
1. What's the context in the .bin file?
I use the matlab code 'A = fread(bin_file,'ubit8');' to read the .bin file.
But i am confused about the context. It's not a rectangle or a mask. the size of A is 1496x1, one number per line.
![image](https://github.com/votchallenge/toolkit/assets/28916428/326777c2-5c8c-47aa-8abf-705194491e82)

2. The analysis
I think the format of .bin might be encoded, but can be decoded by the server. So i try to analysis it.
But the report seems wrong.
![image](https://github.com/votchallenge/toolkit/assets/28916428/96157dae-694c-4a60-901e-4cf1bd34b749)
Only the version and time is reported.
At first i think may be it's special for the NCC example.
So I tried to intergate a simple tracker, but report shows no numerical results again.
The data reported to VOT is under the form of List(np.array, np.array,...,number of objects).
I think it's consistent with your new NCC example, ncc_multitarget_mask.py.

So would you mind explain these two questions?

**Comment by Zhangyong-Tang** [comment]
Wether the confidence is a necessary input for the report or not?

**Comment by lukacu** [comment]
The bin file is a new, more compact format for trajectories. It is binary, but is not obfuscated in any way. The reason for empty analysis report os that groundtruth is not public except for the first frame. 

There is no meed to report confidence, it will be ignored. But you have to report of an object is not visible with an empty region (we are upading tutorials on this matter).

**Comment by Zhangyong-Tang** [comment]
You mean we will not get the analysis report anymore, do i understand correctly?

**Comment by lukacu** [comment]
Read participation instructions, there is an evaluation server that you can use.
