### ISSUE TITLE
trax.TraxException: Unable to connect to tracker

### ISSUE THREAD

**Issue by ChengAoZong** [votchallenge/toolkit#96]
hello, i have passed the official test example(NCCPython), but when i test my tracker it's failed, the terminal output is:
![image](https://github.com/votchallenge/toolkit/assets/49490285/3a1dbaa5-5927-4b79-b7fb-4b3a3e44d999)

toolkit-version:0.6.3
I would be very grateful if someone could help me.

**Comment by lukacu** [comment]
This part of the stack trace is not helpful, it does not show the real problem. All that is reported is that communication was not established, either the process was not started correctly or it shut down immediately for some reason. Try using vot test to see more outputs (perhaps also enable debug).

**Comment by ChengAoZong** [comment]
thanks a lot ~

**Comment by lukacu** [comment]
If you have solved your problem with the hint, please close the issue. Otherwise provide more information.

**Comment by tdd233** [comment]
> 您好，我已经通过了官方测试示例（NCCPython），但是当我测试我的跟踪器时它失败了，终端输出是： ![图像](https://user-images.githubusercontent.com/49490285/240585653-3a1dbaa5-5927-4b79-b7fb-4b3a3e44d999.png)
> 
> 工具包版本：0.6.3 如果有人能帮助我，我将不胜感激。

Hi, I met the same error when I used the vots2023 stack. If you have solved the problem, could you please offer some help? Thanks a lot.

**Comment by ChengAoZong** [comment]
> > hello, i have passed the official test example(NCCPython), but when i test my tracker it's failed, the terminal output is： ![图像](https://user-images.githubusercontent.com/49490285/240585653-3a1dbaa5-5927-4b79-b7fb-4b3a3e44d999.png)
> > toolkit-version:0.6.3.I would be very grateful if someone could help me.
> 
> Hi, I met the same error when I used the vots2023 stack. If you have solved the problem, could you please offer some help? Thanks a lot.

this error means your code has something wrong， in this page you can not know anything， you could use vot test to test your tracker，and in that terminal the true error message will be printed

**Comment by lukacu** [comment]
Yes, please first run "vot test" to see details. Also, do not comment on closed issues, open new ones instead if you have problems.
