### ISSUE TITLE
Maybe some bugs in the toolkit

### ISSUE THREAD

**Issue by davidyang180** [votchallenge/toolkit#98]
Hi! After debugging, I found that there may be some bugs in the toolkit. I don't know if this is a problem with the code I wrote, so I will report the bugs found here.
1. Dev dataset evaluation process
When evaluating my tracker on the dev dataset, I found that the Quality metric has been low, but the visualization of the predicted mask is not too wrong.
Because dev dataset provides the ground-truth of the frame, in order to verify the evaluation process, I directly generate the ground-truth mask through the official io.py (it has been visually verified that the generated ground-truth mask matches the image). When evaluating a frame with ground-truth mask provided, directly read the generated ground-truth mask (binary image, the shape is the size of the image) as the report result, and when evaluating a frame without ground-truth mask (the label in groundtruth_*.txt is 0 ), directly reported as `None`.
![image](https://github.com/votchallenge/toolkit/assets/45596935/1a9aa326-4e70-4e6e-b255-8864441ed1b3)

But the Quality metric is also very low. I would like to ask what is the reason for this?

2. Test dataset evaluation process
On the test dataset, when using the vot command to evaluate my tracker, it is found that the shape of the first frame mask received through the `handle.objects()` command is inconsistent with the shape of the picture. 
e.g. animal sequence:
the shape of `handle.objects():` (271, 850)
the shape of image: (720, 1280)
This problem does not arise because the ground-truth of the dev dataset has no mask offset. However, the test data set has a mask offset in the ground-truth labels of some sequences. Is it the offset of the unprocessed mask in the toolkit?

**Comment by lukacu** [comment]
It is not clear completely, but it seems that you are trying to compute overlaps manually (at least some steps). What you have to know is that masks are optimized when they are loaded to memory to reduce memory footprint (e.g. the full groundtruth of 144 sequences takes more than 40GB of memory). Since tracking masks are usually limited to a part of an image we encode only the bounding box of the actual object and an offset. This was used in the past challenges and it worked well. 

I would say that your problem may be related to not taking offset into account. We have computed scores for several trackers and they make sense. But if you have noticed a problem, then please provide a single-frame example where computation of overlap is wrong.

Also, please do not overuse the dev dataset, it has only been released to test the technical aspect of integration.

**Comment by davidyang180** [comment]
> It is not clear completely, but it seems that you are trying to compute overlaps manually (at least some steps). What you have to know is that masks are optimized when they are loaded to memory to reduce memory footprint (e.g. the full groundtruth of 144 sequences takes more than 40GB of memory). Since tracking masks are usually limited to a part of an image we encode only the bounding box of the actual object and an offset. This was used in the past challenges and it worked well.
> 
> I would say that your problem may be related to not taking offset into account. We have computed scores for several trackers and they make sense. But if you have noticed a problem, then please provide a single-frame example where computation of overlap is wrong.
> 
> Also, please do not overuse the dev dataset, it has only been released to test the technical aspect of integration.

Hi! It means that the shape size of the mask obtained by the `handle = vot.VOT("mask",multiobject=True); objects = handle.objects()command` is not equal to the image shape, do we need to handle the offset by ourselves?

**Comment by davidyang180** [comment]
By the way, during the tracking process, is the mask result reported by the tracker a binary image? (e.g. a 2D ndarray of shape (720, 1280) with values 0 or 1)

**Comment by lukacu** [comment]
Yes, the mask is a 2d image, but is encoded during transmission or storage as RLE with an offset.

**Comment by davidyang180** [comment]
> Yes, the mask is a 2d image, but is encoded during transmission or storage as RLE with an offset.
Hi! When I report the tracker results through the toolkit, you can see from the figure below that the first frame of ground truth mask printed by the trax server is a correct RLE encoding.
![image](https://github.com/votchallenge/toolkit/assets/45596935/5e2e4d14-dcd5-4cdf-ba80-c339d492ba64)
But during the tracking process, the tracker reports 2d image mask, but the intermediate tracker result printed by the trax server only has offset and size. Is this normal?
![image](https://github.com/votchallenge/toolkit/assets/45596935/09778fde-f505-4e44-8c3c-acaebf9d5c3c)

**Comment by lukacu** [comment]
The state looks like an empty mask. It has a full dimensions of the input frame, but no foreground pixels that need encoding. The offset is optional and can be used to reduce size of a mask. 

But there is a small issue that was perhaps not explained enough: trax protocol does not really know the size of an image so if the mask is truncated, the top-left corner can be recovered due to the offset, but the bottom and right empty parts are not recovered automatically. This means that the matrix returned by python wrapper may not have the same size as the input image, you have to pad it with zeros if you want to have same size matrices.

**Comment by lukacu** [comment]
Please close the issue if your questions were answered.

**Comment by davidyang180** [comment]
> The state looks like an empty mask. It has a full dimensions of the input frame, but no foreground pixels that need encoding. The offset is optional and can be used to reduce size of a mask.
> 
> But there is a small issue that was perhaps not explained enough: trax protocol does not really know the size of an image so if the mask is truncated, the top-left corner can be recovered due to the offset, but the bottom and right empty parts are not recovered automatically. This means that the matrix returned by python wrapper may not have the same size as the input image, you have to pad it with zeros if you want to have same size matrices.

Hi! I am sure that there is a bug when trax reports the results. Taking the cat-18 sequence of the dev dataset as an example, I visually verified that the mask output of the tracker has foreground pixels (positive(1) pixels) in the 2nd frame and the 626th frame. But after these two frames are reported, the mask of the 2nd frame is not encoded. What is the problem?
Visualization of the mask in 2nd frame:
![image](https://github.com/votchallenge/toolkit/assets/45596935/df14b42f-8dfe-4ab1-b96a-f6cbd35f4a35)
The result of the tracking mask of the 2nd frame after trax encoding:
![image](https://github.com/votchallenge/toolkit/assets/45596935/df996512-641f-4021-aa6d-9e40c66ad82a)
Visualization of the mask in 626th frame:
![image](https://github.com/votchallenge/toolkit/assets/45596935/2efb02fa-575d-4c2b-9ec9-f543de258d4b)
The result of the tracking mask of the 626th frame after trax encoding:
![image](https://github.com/votchallenge/toolkit/assets/45596935/fa26e5f2-009b-4be4-bd83-e5482a7e41fc)

**Comment by lukacu** [comment]
The code that builds the low level communication has been used in several challenges already and although it was extended to multiple objects this year I find it unlikely that there would be a problem with it. We have also tested it with several trackers and as far as I can tell we found no problems. I will check with other people in the organizing team that have tested other trackers.

The most likely issue that I see is that the input mask is somehow different and not correctly recognized in one of the cases.

**Comment by davidyang180** [comment]
> The code that builds the low level communication has been used in several challenges already and although it was extended to multiple objects this year I find it unlikely that there would be a problem with it. We have also tested it with several trackers and as far as I can tell we found no problems. I will check with other people in the organizing team that have tested other trackers.
> 
> The most likely issue that I see is that the input mask is somehow different and not correctly recognized in one of the cases.

Hi! The code that has just been debugged has been able to encode the corresponding mask. But I just added a few extra lines of code to make the mask regenerate the same mask. Although the two are exactly the same from the top-level code, it is successful to regenerate the same mask.
I think this may involve low-level coding issues, I have not yet been able to find this bug.
