### ISSUE TITLE
tool-kit version 0.6.3 install issue

### ISSUE THREAD

**Issue by JornyWan** [votchallenge/toolkit#99]
Hi, I have used pip install vot-tool kit ( --upgrade as well) but i can just have the version of 0.6.2 of vot-toolkit but not 0.6.3

Also, I want to evaluate your official ncc_multiobject_mask tracker with the stack "tests/multiobject", i use vot evaluate --workspace 'path/to/workspace/' tracker-name, but i received the following error:

can you help me fix that?

<img width="935" alt="image" src="https://github.com/votchallenge/toolkit/assets/97571309/f6069221-6659-4df0-a5cf-b9e23ea597b4">

**Comment by alanlukezic** [comment]
Hi, I have just run the same tracker on the same dataset without any issues using the toolkit version 0.6.3. What is the reason for not upgrading the toolkit to the latest version? Have you tried removing all files and folders from the workspace directory and initializing it again?

**Comment by lukacu** [comment]
We are working on automating release publishing to PyPi. While releases are still manual, there can be some delays, it is best to always check Github as well and install from the repository if possible.

**Comment by JornyWan** [comment]
hi, i have installed 0.6.3, but when i do vot evaluate:

i meet a error with 'cache' argument

![image](https://github.com/votchallenge/toolkit/assets/97571309/eb2fe59d-bcaa-4e53-a5e3-aa2a0130d2f5)

**Comment by lukacu** [comment]
These issue should be fixed now, version 0.6.4 is available on pypi.

**Comment by lukacu** [comment]
Please close the issue if the error is now gone.
